name: Build TechnicalMundeer Kernel
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Locate Build Script
        run: |
          # Yeh command dikha degi ki file kahan hai
          find . -name "build_kernel.py"

      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential flex libc6-dev libncurses5-dev libssl-dev python3 clang llvm lld

      - name: Build TechnicalMundeer Kernel
        run: |
          # Yahan file mil jayegi, hum uska sahi path use karenge
          # Agar script root mein nahi mili, toh 'find' command batayegi ki kahan hai
          python3 $(find . -name "build_kernel.py") --target m31 --oneui
